### ISSUE TITLE
As a User, I want to generate my custom action for my smart contract

### ISSUE THREAD

**Issue by danielAlvess** [lecle/aloxide#60]
Configuration:

```yaml
actions:
  - name: invalidateVote
    fields:
      - name: voteId
        type: uint64_t
     -  name: reason
        type: string
```

generated action: 

EOS: 
```c++
[[eosio::action]] void invalidvote(uint64_t voteId, string reason) {
}
```

ICON: 
```python
@external
def invalidvote(self, voteId: int, reason: string):
  
```
